export class FirebaseClient{
 constructor(config){this.config=config;this.ready=!!config.enabled&&config.firebase?.projectId==='onet-kochi'&&!!config.appCheck?.siteKey;this.auth=null;this.listener=()=>{}}
 async initialize(){if(this.initializing)return this.initializing;this.initializing=this.setup().catch(e=>{this.initializing=null;throw e});return this.initializing}
 async setup(){if(!this.ready)throw Error('Browser security registration is not ready yet. Local play remains available.');if(this.auth)return;if(!this.config.allowedHosts.includes(location.hostname))throw Error('This browser address has not been approved for KOCHI sign-in.');const base='https://www.gstatic.com/firebasejs/12.19.0/';const [app,A,C,F]=await Promise.all(['app','auth','app-check','functions'].map(n=>import(base+`firebase-${n}.js`)));this.A=A;this.C=C;this.F=F;const firebase=app.initializeApp(this.config.firebase,'KOCHI-Web');this.check=C.initializeAppCheck(firebase,{provider:new C.ReCaptchaEnterpriseProvider(this.config.appCheck.siteKey),isTokenAutoRefreshEnabled:true});this.auth=A.getAuth(firebase);await A.setPersistence(this.auth,A.browserLocalPersistence);this.functions=F.getFunctions(firebase,'us-central1');await this.auth.authStateReady();A.onAuthStateChanged(this.auth,u=>this.listener(u));}
 async connect(){await this.initialize();if(!this.auth.currentUser)await this.A.signInAnonymously(this.auth);return this.auth.currentUser}
 async call(name,data){await this.initialize();await this.C.getToken(this.check,false);return (await this.F.httpsCallable(this.functions,name)(data)).data}
 async signIn(provider,open=false){await this.initialize();let p;if(provider==='google'){p=new this.A.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'})}else{p=new this.A.OAuthProvider('apple.com');p.addScope('email');p.addScope('name')}if(open){return (await this.A.signInWithPopup(this.auth,p)).user}if(!this.auth.currentUser)await this.A.signInAnonymously(this.auth);return (await this.A.linkWithPopup(this.auth.currentUser,p)).user}
 async email(email,password,open){await this.initialize();if(open)return (await this.A.signInWithEmailAndPassword(this.auth,email,password)).user;if(!this.auth.currentUser)await this.A.signInAnonymously(this.auth);return (await this.A.linkWithCredential(this.auth.currentUser,this.A.EmailAuthProvider.credential(email,password))).user}
 async signOut(){if(this.auth)await this.A.signOut(this.auth)}
 async reset(email){await this.initialize();await this.A.sendPasswordResetEmail(this.auth,email)}
 async verify(){if(!this.auth?.currentUser)throw Error('Open your email account first.');await this.A.sendEmailVerification(this.auth.currentUser)}
}
