import * as G from './game.js';
export function invitationCode(input){let value=String(input).trim();if(/^https?:\/\//i.test(value)){const u=new URL(value);value=u.searchParams.get('invite')??''}value=value.replace(/\s/g,'');if(!/^[a-f0-9]{32}$/i.test(value))throw Error('Paste the full invitation or invitation link.');return value.toLowerCase()}
export function seconds(match,player,received,now){if(!match?.clock)return null;const c=match.clock;const elapsed=match.status==='active'&&match.state.turn===player?Math.max(0,match.serverNow-c.turnStartedAt)+Math.max(0,now-received):0;return Math.ceil(Math.max(0,(c.remainingMs[player]??0)-elapsed)/1000)}
export function validateMatch(m){if(!m)return null;if(typeof m.id!=='string'||!Array.isArray(m.state?.board)||m.state.board.length!==9||!m.state.board.every(x=>x===null||x==='black'||x==='white')||!['black','white'].includes(m.state.turn)||!Number.isInteger(m.state.sequence)||m.state.sequence<0||typeof m.status!=='string'||!Number.isFinite(m.serverNow)||!m.players)throw Error('The server match could not be read. Reconnect to check it.');return m}
const friendlyError=e=>({'auth/network-request-failed':'Connection unavailable. Check your internet connection and retry.','auth/popup-blocked':'Allow the sign-in window, then retry.','auth/popup-closed-by-user':'Sign-in cancelled. Your current journey was kept.','auth/unauthorized-domain':'This browser address has not been approved for sign-in.','auth/invalid-credential':'That email or password could not be verified.','functions/unavailable':'The shared courtyard is temporarily unavailable. Retry shortly.'}[e.code]??e.message??'Connection unavailable.');
const terminal=new Set(['functions/failed-precondition','functions/permission-denied','functions/not-found']);
export class OnlineSession{
 constructor({transport,storage,now=()=>performance.now(),id=()=>crypto.randomUUID(),onChange=()=>{}}){Object.assign(this,{transport,storage,now,id,onChange});this.uid=null;this.linked=false;this.match=null;this.players={};this.profile=null;this.social=null;this.rankings=null;this.backup=null;this.cloudChecked=false;this.cloudConflict=false;this.searching=false;this.pending=null;this.selected=null;this.received=0;this.connectionLost=false;this.busy=false;this.notice='Connect to play across devices.';this.epoch=0}
 get locked(){return this.searching||['active','waiting'].includes(this.match?.status)}
 get ready(){return this.transport.ready}
 get stateGame(){return this.match?{board:this.match.state.board,turn:this.match.state.turn,history:[]}:null}
 emit(){this.onChange()}
 identity(user){const uid=user?.uid??null;if(uid!==this.uid){this.epoch++;this.uid=uid;this.match=null;this.players={};this.profile=null;this.social=null;this.rankings=null;this.backup=null;this.cloudChecked=false;this.cloudConflict=false;this.searching=false;this.selected=null;this.connectionLost=false;this.busy=false;this.pending=uid?this.read(`pending.${uid}`):null}this.linked=!!user&&!user.isAnonymous;this.user=user;this.emit()}
 read(k){try{return JSON.parse(this.storage.getItem(`kochi.web.online.${k}`)??'null')}catch{return null}}
 write(k,v){this.storage.setItem(`kochi.web.online.${k}`,JSON.stringify(v))}
 remove(k){this.storage.removeItem(`kochi.web.online.${k}`)}
 async call(name,data={}){const uid=this.uid,epoch=this.epoch;if(!uid)throw Error('Connect first.');const value=await this.transport.call(name,data);if(uid!==this.uid||epoch!==this.epoch)throw Error('Account changed. Retry from the current profile.');return value}
 async run(fn,background=false){if(background){if(this.polling||this.busy)return;const epoch=this.epoch;this.polling=true;try{await fn()}catch(e){if(epoch===this.epoch){this.connectionLost=!!this.match;this.notice=e.message??'Connection interrupted.'}}finally{this.polling=false;this.emit()}return}if(this.busy)return;const epoch=this.epoch;this.busy=true;this.emit();try{await fn()}catch(e){if(epoch!==this.epoch)return;this.notice=e.code==='auth/account-exists-with-different-credential'||e.code==='auth/credential-already-in-use'?'This sign-in belongs to another KOCHI account. Choose Open existing account; journeys are not merged.':friendlyError(e);if(this.match)this.connectionLost=true;}finally{if(epoch===this.epoch){this.busy=false;this.emit()}}}
 async connect(){this.connecting=true;try{const user=await this.transport.connect();this.identity(user);this.profile=await this.call('getProfile');await this.resume();this.notice='Connected.';this.emit()}finally{this.connecting=false}}
 async resume(){this.accept((await this.call('resumeMatch')).match??null);await this.refreshPlayers()}
 accept(m){m=validateMatch(m);if(m&&this.match?.id===m.id&&(m.state.sequence<this.match.state.sequence||this.match.status==='finished'&&m.status==='active'))return;if(this.match?.id!==m?.id||this.match?.state.sequence!==m?.state.sequence)this.selected=null;if(this.match?.id!==m?.id||JSON.stringify(this.match?.players)!==JSON.stringify(m?.players))this.players={};this.match=m;this.received=this.now();this.connectionLost=false;if(this.pending&&this.pending.uid===this.uid&&m&&(this.pending.matchId!==m.id||m.status!=='active'||m.state.sequence>this.pending.sequence))this.clearPending();this.notice=m?(m.status==='waiting'?'Share your invitation to start a casual game.':m.status==='active'?'Connected to your opponent.':'Match finished.'):'Connected. Choose a game.';this.emit()}
 async refreshPlayers(){const m=this.match;if(!m)return;const people=await this.call('getMatchPlayers',{matchId:m.id});if(this.match?.id===m.id&&JSON.stringify(this.match.players)===JSON.stringify(m.players)){this.players=people;this.emit()}}
 async create(){if(this.locked)throw Error('Finish or leave your current match first.');this.accept(await this.call('createFriendMatch'));await this.refreshPlayers()}
 async join(input){if(this.locked)throw Error('Finish or leave your current match first.');this.accept(await this.call('joinFriendMatch',{matchId:invitationCode(input)}));await this.refreshPlayers()}
 async find(mode='ranked'){if(this.match&&this.locked)throw Error('Finish or leave your match first.');const r=await this.call('findMatch',{mode});this.searching=!!r.searching;this.accept(r.match??null);if(this.match)await this.refreshPlayers()}
 async cancel(){const r=await this.call('cancelSearch');this.searching=!!r.searching;this.accept(r.match??null)}
 async poll(){if(this.match){const id=this.match.id;const snapshot=await this.call('getMatch',{matchId:id});if(this.match?.id!==id)return;this.accept(snapshot);if(this.match?.rematchId){const rematchId=this.match.rematchId;const rematch=await this.call('getMatch',{matchId:rematchId});if(this.match?.id!==id)return;this.accept(rematch)}if(!Object.keys(this.players).length)await this.refreshPlayers()}else if(this.searching)await this.find('ranked')}
 async leave(){if(!this.match)return;await this.call('leaveMatch',{matchId:this.match.id});this.accept(null);this.clearPending()}
 async rematch(){if(!this.match)return;const r=await this.call('requestRematch',{matchId:this.match.id});this.accept(r.match??null)}
 clearPending(){if(this.uid)this.remove(`pending.${this.uid}`);this.pending=null}
 async tap(point){const m=this.match;if(!m||m.status!=='active'||m.players[m.state.turn]!==this.uid||this.pending||this.connectionLost)return;const g=this.stateGame;if(!G.placing(g)&&g.board[point]===g.turn){this.selected=this.selected===point?null:point;this.emit();return}const action={from:G.placing(g)?null:this.selected,to:point};if(!G.legal(g).some(a=>a.from===action.from&&a.to===action.to))throw Error('Choose your stone, then an empty connected point.');const p={uid:this.uid,matchId:m.id,commandId:this.id(),sequence:m.state.sequence,action};this.write(`pending.${this.uid}`,p);this.pending=p;this.emit();await this.sendPending()}
 async sendPending(){const p=this.pending;if(!p)return this.resume();if(p.uid!==this.uid)throw Error('Account changed. Reconnect.');try{const m=await this.call('submitMove',{matchId:p.matchId,commandId:p.commandId,sequence:p.sequence,action:p.action});this.accept(m);this.clearPending()}catch(e){if(terminal.has(e.code)){this.clearPending();await this.resume()}else this.connectionLost=true;throw e}}
 async saveProfile(name,country,avatar){if(this.locked)throw Error('Finish your match first.');await this.call('saveProfile',{displayName:name,countryCode:country.toUpperCase(),avatarId:avatar});this.profile=await this.call('getProfile');this.notice='Profile saved.'}
 async getBackup(){if(!this.linked||this.locked)throw Error('Open an account and finish your match first.');this.cloudChecked=false;const r=await this.call('getProgressBackup',{ownerUID:this.uid});this.backup=r.backup??null;this.cloudChecked=true;this.notice=this.backup?'Cloud journey found. Choose explicitly which journey to keep.':'No cloud journey found for this account.'}
 async saveBackup(progress){if(!this.linked||this.locked||!this.cloudChecked)throw Error('Check the cloud journey first.');const k=`backup.${this.uid}`,old=this.read(k);const payload=old&&JSON.stringify(old.progress)===JSON.stringify(progress)?old:{ownerUID:this.uid,progress,revision:this.backup?.revision??0,requestID:this.id()};this.write(k,payload);const r=await this.call('saveProgressBackup',payload);this.backup=r.backup??null;this.remove(k);this.cloudConflict=!!r.conflict;if(r.conflict){this.notice='Both journeys changed. Check the cloud and choose which whole journey to keep.';return false}this.notice='Browser journey saved to cloud.';return true}
 async friends(){this.social=await this.call('socialList')}
 async ranks(scope){this.rankings=await this.call('worldLeaderboard',{scope})}
 async requestFriend(uid){await this.call('requestFriend',{uid:uid.trim()});await this.friends()}
 async respondFriend(uid,accept){await this.call('respondFriend',{uid,accept});await this.friends()}
}
