import {winner} from './game.js';
export const regular=['hiro','zara','olivia','marco','luna','sujith'];
export const all=[...regular,'kai','onet'];
export const initial=()=>({schemaVersion:1,xp:0,completedMatches:0,aiMatches:0,wins:{},completedIDs:[],boostedIDs:[],guardianWon:false,lessonStep:0,hasMetDev:false,seenRewards:[],equipped:{background:'background.classic',board:'board.classic',stones:'stones.classic',overlay:'overlay.black',avatar:'avatar.owl'}});
export const mastered=p=>regular.filter(id=>(p.wins[id]??0)>=3).length;
export const mystery=p=>p.wins.onet>0?4:p.guardianWon?3:mastered(p)===6&&p.completedMatches>=40?2:mastered(p)>=2?1:0;
export function canChallenge(p,id){if(id==='onet')return mystery(p)>=3;if(id==='kai')return mastered(p)>=3&&p.lessonStep>=40;const i=regular.indexOf(id);return i>=0&&(i===0||p.wins[regular[i-1]]>0||p.aiMatches>=i*5)}
export const requirement=(p,id)=>id==='kai'?`Finish 40 lessons and master 3 opponents (${mastered(p)}/3)`:id==='onet'?'Complete the guardian challenge':regular.indexOf(id)<=0?'Ready to play':`Defeat ${regular[regular.indexOf(id)-1]} or finish ${regular.indexOf(id)*5} AI matches (${p.aiMatches}/${regular.indexOf(id)*5})`;
export function record(p,id,g,opponent,guardian=false){if(!winner(g)||p.completedIDs.includes(id)||opponent&&!canChallenge(p,opponent)||guardian&&(opponent!=='sujith'||mystery(p)!==2))return p;const won=opponent&&winner(g)==='black';return {...p,xp:p.xp+20+(won?20:0),completedMatches:p.completedMatches+1,aiMatches:p.aiMatches+(opponent?1:0),wins:won?{...p.wins,[opponent]:(p.wins[opponent]??0)+1}:p.wins,completedIDs:[...p.completedIDs,id],guardianWon:p.guardianWon||guardian&&!!won}}
export function rewards(c){const out=[];c.skins.filter(s=>!all.includes(s.id)&&s.id!=='classic').forEach((s,i)=>['background','board','stones'].forEach(k=>out.push({id:`${k}.${s.id}`,kind:k,name:s.name,file:k==='background'?s.background:k==='board'?s.board:s.p1,xp:(i+1)*160})));c.skins.filter(s=>all.includes(s.id)||s.id==='classic').forEach(s=>['background','stones','board'].forEach((k,i)=>out.push({id:`${k}.${s.id}`,kind:k,name:s.name,file:k==='background'?s.background:k==='board'?s.board:s.p1,opponent:s.id==='classic'?null:s.id,wins:s.id==='classic'?0:s.id==='onet'?1:i+1,xp:0})));['avatar','overlay','background'].forEach(k=>c.items.filter(x=>x.kind===k).forEach((x,i)=>out.push({...x,xp:['overlay.black','avatar.owl'].includes(x.id)?0:(i+1)*(k==='background'?120:80)})));return out.sort((a,b)=>a.id.localeCompare(b.id))}
export const unlocked=(p,r)=>r.opponent?(p.wins[r.opponent]??0)>=r.wins:p.xp>=r.xp;
export const rewardRequirement=(p,r)=>r.opponent?`${Math.min(p.wins[r.opponent]??0,r.wins)}/${r.wins} wins against ${r.opponent}`:`${Math.min(p.xp,r.xp)}/${r.xp} XP`;
